# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C_PROJECT/UI_FILES/mini_meeting_box.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1300, 338)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 10, 1271, 321))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.meeting_id_label = QtWidgets.QLabel(self.frame)
        self.meeting_id_label.setGeometry(QtCore.QRect(20, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Condensed")
        font.setPointSize(18)
        self.meeting_id_label.setFont(font)
        self.meeting_id_label.setObjectName("meeting_id_label")
        self.summary_label = QtWidgets.QLabel(self.frame)
        self.summary_label.setGeometry(QtCore.QRect(40, 50, 811, 21))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        self.summary_label.setFont(font)
        self.summary_label.setObjectName("summary_label")
        self.contrib_table = QtWidgets.QTableWidget(self.frame)
        self.contrib_table.setGeometry(QtCore.QRect(30, 80, 971, 171))
        self.contrib_table.setObjectName("contrib_table")
        self.contrib_table.setColumnCount(4)
        self.contrib_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.contrib_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.contrib_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.contrib_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.contrib_table.setHorizontalHeaderItem(3, item)
        self.contrib_table.horizontalHeader().setDefaultSectionSize(240)
        self.view_btn = QtWidgets.QPushButton(self.frame)
        self.view_btn.setGeometry(QtCore.QRect(30, 260, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Courier 10 Pitch")
        font.setPointSize(16)
        self.view_btn.setFont(font)
        self.view_btn.setObjectName("view_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.meeting_id_label.setText(_translate("Form", "Meeting 1"))
        self.summary_label.setText(_translate("Form", "📅  2025-03-25  |  💰 Total: Ksh. 12000  | Required: Ksh. 300  | Type: Standard"))
        item = self.contrib_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Full Name"))
        item = self.contrib_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Amount"))
        item = self.contrib_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Method Of Payment"))
        item = self.contrib_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Date Paid"))
        self.view_btn.setText(_translate("Form", "View The Meeting"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
